name: flutter_onboard
description: A simple, elegant and easy to use onboard widget for both android and ios devices.
version: 0.1.0
homepage:
repository: https://github.com/praharshbhatt/flutter_onboard

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
